STEERING_MIN = -32767 
ACCELERATOR_MAX = 65535

# button index for Logitech G920 steering wheel controller 
BUTTON_A_INDEX = 0 
BUTTON_B_INDEX = 1 
BUTTON_X_INDEX = 2 
BUTTON_Y_INDEX = 3 
BUTTON_UP_INDEX = 4 
BUTTON_DOWN_INDEX = 5 
BUTTON_MENU_INDEX = 6 
BUTTON_VIEW_INDEX = 7 
BUTTON_RSB_INDEX = 8 
BUTTON_LSB_INDEX = 9 
BUTTON_XBOX_INDEX = 10 
